jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use GitHub PAT (if needed in your workflow)
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "Using GitHub PAT for additional GitHub-related actions"
          # Your commands that require GitHub PAT
